name: shroom
description: 
  Flexible, minimalistic, and fast Graph Database for Dart and Flutter.
  GraphQL/GraphDB/Graph Database
version: 1.0.1
repository: https://github.com/monki1/shroom_dart

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  sqlite3: ^2.4.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
