name: shroom
description: Database, a shroom is a node that stores data.Edges can be stored as data in Nodes.
version: 1.0.0
repository: https://github.com/monki1/shroom_dart

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  sqlite3: ^2.4.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
